### ISSUE TITLE
Transform JWT to Session

### ISSUE THREAD

**Issue by HeitorMatt** [harena-lab/harena-manager#96]

**Comment by HeitorMatt** [comment]
Done on session development: Login and logout working. 
WIP: Transform requests to js files, instead of adonis controllers

**Comment by faguim** [comment]
Time to celebrate

**Comment by faguim** [comment]
Maybe, rest DCC is an alternative to transform requests to js files, once DCC keeps the REST request on the .edge files. 

DCC solves 2 of our problems: adonis Controllers and pure javascript (???)

**Comment by HeitorMatt** [comment]
You are right, I'm waiting for dcc-rest to be ready
