### ISSUE TITLE
Solution to Postman shared workspace limit

### ISSUE THREAD

**Issue by faguim** [harena-lab/harena-manager#98]
As discussed in slack, we need to pick a Postman alternative.

As a temporary solution, I'll commit the collection exported from Postman. Whenever some update is need, this file must be commited by the change author.

@santanche @marcosfmmota @HeitorMatt @matheusmota any suggestions about this issue?

**Comment by HeitorMatt** [comment]
We could allocate the file to a private repository. To avoid sensitive information being leaked.
